### ISSUE TITLE
Video is not muted for many users (cannot reproduce)

### ISSUE THREAD

**Issue by hattifn4ttar** [hattifn4ttar/youtube_supportfreemedia#10]

**Comment by hattifn4ttar** [comment]
I am trying to mute video by clicking on a button, but some users say it doesn't work for them (I guess the button element is not found in player?).

Also added mute function with document.dispatchEvent for the case when button element is not found, but in this case I cannot check if sound is on when the button is not found.

**Comment by orbifolia** [comment]
@hattifn4ttar may be this one?

https://developer.chrome.com/docs/extensions/reference/tabs/#mute-the-specified-tab

**Comment by hattifn4ttar** [comment]
Hi @orbifolia, sorry I missed you message. We decided to change the direction a bit and make an accent on manual promotion and notifications. This was recommended by people from Anonymous team and some content creators. 

We keep an option to play video automatically, but disabled features that can look suspicious for YouTube algorithms - automated likes and muting videos.
